name: Hamonize CI
on:
  push:
    branches: [ master ]
jobs:          
  build-agent:
    name: Build Hamonize-agent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install debhelper npm
        
      - name: Build Hamonize-agent
        run: cd hamonize-agent/ && sudo dpkg-buildpackage -b -us -uc -ui
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hamonize-agent
          path: ./hamonize-agent_*.deb
          
  build-connect:
    name: Build Hamonize-connect
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install debhelper npm
        
      - name: Build Hamonize-connect
        run: cd hamonize-connector/ && sudo dpkg-buildpackage -b -us -uc -ui
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hamonize-connect
          path: ./hamonize-connect_*.deb

  build-admin:
    name: Build Hamonize-admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install g++ make cmake qtbase5-dev qtbase5-dev-tools qttools5-dev qttools5-dev-tools libqca-qt5-2-plugins xorg-dev libxtst-dev libjpeg-dev zlib1g-dev libssl-dev libpam0g-dev libprocps-dev liblzo2-dev libqca-qt5-2-dev libldap2-dev libsasl2-dev
        
      - name: Build Hamonize-admin
        run: cd hamonize-admin/ && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr .. && fakeroot make package
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hamonize-admin
          path: ./hamonize-admin_*.deb
