name: Hamonize CI
on:
  push:
    branches: [ master ]
jobs:
  build-agent:
    name: Build Hamonize-agent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Hamonize ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: false
          prerelease: false
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install debhelper npm
        
      - name: Build
        run: cd hamonize-agent/ && sudo dpkg-buildpackage -b -us -uc -ui
          
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./hamonize-agent_1.0.1_amd64.deb
          asset_name: hamonize-agent_1.0.1_amd64.deb
          asset_content_type: application/deb
      
  build-connector:
    name: Build Hamonize-connector
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install debhelper npm
        
      - name: Build
        run: cd hamonize-connector/ && sudo dpkg-buildpackage -b -us -uc -ui
          
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./hamonize-connect_1.0.1_amd64.deb
          asset_name: hamonize-connect_1.0.1_amd64.deb
          asset_content_type: application/deb

  build-connector-win:
    name: Build Hamonize-connector-win
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install debhelper npm
        
      - name: Build
        run: cd hamonize-connector-window && npm install && npm run build:win

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./hamonize-connector-window/dist/'hamonize-connect Setup 1.0.6.exe'
          asset_name: 'hamonize-connect Setup 1.0.6.exe'
          asset_content_type: application/exe
