name: Hamonize CI
on:
  push:
    branches: [ master ]
jobs:
  build-agent:
    name: Build Hamonize-agent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install debhelper npm
      - name: Build
        run: cd hamonize-agent/ && sudo dpkg-buildpackage -b -us -uc -ui
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hamonize-agent
          path: {{ github.workspace }}/hamonize-agent*.deb
      
  # build-linux:
  #   strategy:
  #     matrix:
  #       dist:
  #         - centos.8.3
  #         - debian.buster
  #         - fedora.34
  #         - opensuse.15.2
  #         - ubuntu.focal
  #   runs-on: ubuntu-latest
  #   container: veyon/ci.linux.${{matrix.dist}}
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #     - run: .ci/linux.${{matrix.dist}}/script.sh $GITHUB_WORKSPACE /tmp