# name: Create comment on PR when check-commit fail
# on:
#   workflow_run:
#     workflows: ["Check Commit Message"]
#     types:
#       - completed
# jobs:          
#   comment:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
#     steps:
#       - name: Download artifacts
#         uses: dawidd6/action-download-artifact@v2
#         with:
#           github_token: ${{secrets.GITHUB_TOKEN}}
#           workflow: check-commit.yml
#           workflow_conclusion: failure
#           name: event-number
#           run: echo "event_number=$(cat event_number.txt)" >> $GITHUB_ENV

#       - uses: actions/github-script@v3
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#           script: |
#             github.issues.createComment({
#               issue_number: $event_number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               body: '👋 Thanks for reporting!'
#             })
