name: Hamonize CI
on:
  workflow_run:
    workflows: ["Hamonize CI"]
    types:
      - completed
jobs:          
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: hamonize-agent
          path: hamonize_agent*.deb
  
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Hamonize ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: false
          prerelease: false
          
      - name: Rename Package
        run: mv ./hamonize-agent*.deb ./hamonize-agent_${{ steps.tag_version.outputs.new_tag }}_amd64.deb
          
      - name: Upload Release Asset Agent
        id: upload-release-asset-agent
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hamonize-agent_${{ steps.tag_version.outputs.new_tag }}_amd64.deb
          asset_name: hamonize-agent_${{ steps.tag_version.outputs.new_tag }}_amd64.deb
          asset_content_type: application/deb
